//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dynamic_params package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dynamic_params__UNITEDSOCCERVISIONRECONFCONFIG_H__
#define __dynamic_params__UNITEDSOCCERVISIONRECONFCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dynamic_params
{
  class UnitedSoccerVisionReconfConfigStatics;

  class UnitedSoccerVisionReconfConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(UnitedSoccerVisionReconfConfig &config, const UnitedSoccerVisionReconfConfig &max, const UnitedSoccerVisionReconfConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const UnitedSoccerVisionReconfConfig &config1, const UnitedSoccerVisionReconfConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, UnitedSoccerVisionReconfConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const UnitedSoccerVisionReconfConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, UnitedSoccerVisionReconfConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const UnitedSoccerVisionReconfConfig &config) const = 0;
      virtual void getValue(const UnitedSoccerVisionReconfConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T UnitedSoccerVisionReconfConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (UnitedSoccerVisionReconfConfig::* field);

      virtual void clamp(UnitedSoccerVisionReconfConfig &config, const UnitedSoccerVisionReconfConfig &max, const UnitedSoccerVisionReconfConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const UnitedSoccerVisionReconfConfig &config1, const UnitedSoccerVisionReconfConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, UnitedSoccerVisionReconfConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const UnitedSoccerVisionReconfConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, UnitedSoccerVisionReconfConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const UnitedSoccerVisionReconfConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const UnitedSoccerVisionReconfConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, UnitedSoccerVisionReconfConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, UnitedSoccerVisionReconfConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<UnitedSoccerVisionReconfConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(UnitedSoccerVisionReconfConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("H_Max"==(*_i)->name){H_Max = boost::any_cast<int>(val);}
        if("H_Min"==(*_i)->name){H_Min = boost::any_cast<int>(val);}
        if("S_Max"==(*_i)->name){S_Max = boost::any_cast<int>(val);}
        if("S_Min"==(*_i)->name){S_Min = boost::any_cast<int>(val);}
        if("V_Max"==(*_i)->name){V_Max = boost::any_cast<int>(val);}
        if("V_Min"==(*_i)->name){V_Min = boost::any_cast<int>(val);}
        if("Erode"==(*_i)->name){Erode = boost::any_cast<int>(val);}
        if("Dilate"==(*_i)->name){Dilate = boost::any_cast<int>(val);}
        if("FH_Max"==(*_i)->name){FH_Max = boost::any_cast<int>(val);}
        if("FH_Min"==(*_i)->name){FH_Min = boost::any_cast<int>(val);}
        if("FS_Max"==(*_i)->name){FS_Max = boost::any_cast<int>(val);}
        if("FS_Min"==(*_i)->name){FS_Min = boost::any_cast<int>(val);}
        if("FV_Max"==(*_i)->name){FV_Max = boost::any_cast<int>(val);}
        if("FV_Min"==(*_i)->name){FV_Min = boost::any_cast<int>(val);}
        if("FErode"==(*_i)->name){FErode = boost::any_cast<int>(val);}
        if("FDilate"==(*_i)->name){FDilate = boost::any_cast<int>(val);}
        if("debug_ball"==(*_i)->name){debug_ball = boost::any_cast<bool>(val);}
        if("ball_no"==(*_i)->name){ball_no = boost::any_cast<int>(val);}
        if("ball_area_min"==(*_i)->name){ball_area_min = boost::any_cast<double>(val);}
        if("ball_area_max"==(*_i)->name){ball_area_max = boost::any_cast<int>(val);}
        if("ball_area_ratio"==(*_i)->name){ball_area_ratio = boost::any_cast<double>(val);}
        if("ball_wh_ratio_min"==(*_i)->name){ball_wh_ratio_min = boost::any_cast<double>(val);}
        if("ball_wh_ratio_max"==(*_i)->name){ball_wh_ratio_max = boost::any_cast<double>(val);}
        if("ball_percent_white"==(*_i)->name){ball_percent_white = boost::any_cast<int>(val);}
      }
    }

    int H_Max;
int H_Min;
int S_Max;
int S_Min;
int V_Max;
int V_Min;
int Erode;
int Dilate;
int FH_Max;
int FH_Min;
int FS_Max;
int FS_Min;
int FV_Max;
int FV_Min;
int FErode;
int FDilate;
bool debug_ball;
int ball_no;
double ball_area_min;
int ball_area_max;
double ball_area_ratio;
double ball_wh_ratio_min;
double ball_wh_ratio_max;
int ball_percent_white;

    bool state;
    std::string name;

    
}groups;



//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int H_Max;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int H_Min;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int S_Max;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int S_Min;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int V_Max;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int V_Min;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int Erode;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int Dilate;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int FH_Max;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int FH_Min;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int FS_Max;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int FS_Min;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int FV_Max;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int FV_Min;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int FErode;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int FDilate;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool debug_ball;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int ball_no;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double ball_area_min;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int ball_area_max;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double ball_area_ratio;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double ball_wh_ratio_min;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double ball_wh_ratio_max;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int ball_percent_white;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("UnitedSoccerVisionReconfConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const UnitedSoccerVisionReconfConfig &__max__ = __getMax__();
      const UnitedSoccerVisionReconfConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const UnitedSoccerVisionReconfConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const UnitedSoccerVisionReconfConfig &__getDefault__();
    static const UnitedSoccerVisionReconfConfig &__getMax__();
    static const UnitedSoccerVisionReconfConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const UnitedSoccerVisionReconfConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void UnitedSoccerVisionReconfConfig::ParamDescription<std::string>::clamp(UnitedSoccerVisionReconfConfig &config, const UnitedSoccerVisionReconfConfig &max, const UnitedSoccerVisionReconfConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class UnitedSoccerVisionReconfConfigStatics
  {
    friend class UnitedSoccerVisionReconfConfig;

    UnitedSoccerVisionReconfConfigStatics()
    {
UnitedSoccerVisionReconfConfig::GroupDescription<UnitedSoccerVisionReconfConfig::DEFAULT, UnitedSoccerVisionReconfConfig> Default("Default", "", 0, 0, true, &UnitedSoccerVisionReconfConfig::groups);
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.H_Max = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.H_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.H_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("H_Max", "int", 0, "H Max", "", &UnitedSoccerVisionReconfConfig::H_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("H_Max", "int", 0, "H Max", "", &UnitedSoccerVisionReconfConfig::H_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.H_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.H_Min = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.H_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("H_Min", "int", 0, "H Min", "", &UnitedSoccerVisionReconfConfig::H_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("H_Min", "int", 0, "H Min", "", &UnitedSoccerVisionReconfConfig::H_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.S_Max = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.S_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.S_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("S_Max", "int", 0, "S Max", "", &UnitedSoccerVisionReconfConfig::S_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("S_Max", "int", 0, "S Max", "", &UnitedSoccerVisionReconfConfig::S_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.S_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.S_Min = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.S_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("S_Min", "int", 0, "S Min", "", &UnitedSoccerVisionReconfConfig::S_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("S_Min", "int", 0, "S Min", "", &UnitedSoccerVisionReconfConfig::S_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.V_Max = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.V_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.V_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("V_Max", "int", 0, "V Max", "", &UnitedSoccerVisionReconfConfig::V_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("V_Max", "int", 0, "V Max", "", &UnitedSoccerVisionReconfConfig::V_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.V_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.V_Min = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.V_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("V_Min", "int", 0, "V Min", "", &UnitedSoccerVisionReconfConfig::V_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("V_Min", "int", 0, "V Min", "", &UnitedSoccerVisionReconfConfig::V_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Erode = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Erode = 15;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Erode = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("Erode", "int", 0, "Erode", "", &UnitedSoccerVisionReconfConfig::Erode)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("Erode", "int", 0, "Erode", "", &UnitedSoccerVisionReconfConfig::Erode)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Dilate = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Dilate = 15;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Dilate = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("Dilate", "int", 0, "Dilate", "", &UnitedSoccerVisionReconfConfig::Dilate)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("Dilate", "int", 0, "Dilate", "", &UnitedSoccerVisionReconfConfig::Dilate)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FH_Max = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FH_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FH_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FH_Max", "int", 0, "FH Max", "", &UnitedSoccerVisionReconfConfig::FH_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FH_Max", "int", 0, "FH Max", "", &UnitedSoccerVisionReconfConfig::FH_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FH_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FH_Min = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FH_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FH_Min", "int", 0, "FH Min", "", &UnitedSoccerVisionReconfConfig::FH_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FH_Min", "int", 0, "FH Min", "", &UnitedSoccerVisionReconfConfig::FH_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FS_Max = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FS_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FS_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FS_Max", "int", 0, "FS Max", "", &UnitedSoccerVisionReconfConfig::FS_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FS_Max", "int", 0, "FS Max", "", &UnitedSoccerVisionReconfConfig::FS_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FS_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FS_Min = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FS_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FS_Min", "int", 0, "FS Min", "", &UnitedSoccerVisionReconfConfig::FS_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FS_Min", "int", 0, "FS Min", "", &UnitedSoccerVisionReconfConfig::FS_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FV_Max = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FV_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FV_Max = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FV_Max", "int", 0, "FV Max", "", &UnitedSoccerVisionReconfConfig::FV_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FV_Max", "int", 0, "FV Max", "", &UnitedSoccerVisionReconfConfig::FV_Max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FV_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FV_Min = 255;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FV_Min = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FV_Min", "int", 0, "FV Min", "", &UnitedSoccerVisionReconfConfig::FV_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FV_Min", "int", 0, "FV Min", "", &UnitedSoccerVisionReconfConfig::FV_Min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FErode = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FErode = 15;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FErode = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FErode", "int", 0, "FErode", "", &UnitedSoccerVisionReconfConfig::FErode)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FErode", "int", 0, "FErode", "", &UnitedSoccerVisionReconfConfig::FErode)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FDilate = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FDilate = 15;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FDilate = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FDilate", "int", 0, "FDilate", "", &UnitedSoccerVisionReconfConfig::FDilate)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("FDilate", "int", 0, "FDilate", "", &UnitedSoccerVisionReconfConfig::FDilate)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.debug_ball = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.debug_ball = 1;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.debug_ball = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<bool>("debug_ball", "bool", 0, "Debug Ball", "", &UnitedSoccerVisionReconfConfig::debug_ball)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<bool>("debug_ball", "bool", 0, "Debug Ball", "", &UnitedSoccerVisionReconfConfig::debug_ball)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ball_no = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ball_no = 15;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ball_no = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("ball_no", "int", 0, "Selected Ball", "", &UnitedSoccerVisionReconfConfig::ball_no)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("ball_no", "int", 0, "Selected Ball", "", &UnitedSoccerVisionReconfConfig::ball_no)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ball_area_min = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ball_area_min = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ball_area_min = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<double>("ball_area_min", "double", 0, "Ball Area Min", "", &UnitedSoccerVisionReconfConfig::ball_area_min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<double>("ball_area_min", "double", 0, "Ball Area Min", "", &UnitedSoccerVisionReconfConfig::ball_area_min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ball_area_max = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ball_area_max = 15;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ball_area_max = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("ball_area_max", "int", 0, "Ball Area Max", "", &UnitedSoccerVisionReconfConfig::ball_area_max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("ball_area_max", "int", 0, "Ball Area Max", "", &UnitedSoccerVisionReconfConfig::ball_area_max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ball_area_ratio = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ball_area_ratio = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ball_area_ratio = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<double>("ball_area_ratio", "double", 0, "Ball Area Ratio", "", &UnitedSoccerVisionReconfConfig::ball_area_ratio)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<double>("ball_area_ratio", "double", 0, "Ball Area Ratio", "", &UnitedSoccerVisionReconfConfig::ball_area_ratio)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ball_wh_ratio_min = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ball_wh_ratio_min = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ball_wh_ratio_min = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<double>("ball_wh_ratio_min", "double", 0, "Ball White Area Ratio Min", "", &UnitedSoccerVisionReconfConfig::ball_wh_ratio_min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<double>("ball_wh_ratio_min", "double", 0, "Ball White Area Ratio Min", "", &UnitedSoccerVisionReconfConfig::ball_wh_ratio_min)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ball_wh_ratio_max = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ball_wh_ratio_max = 2.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ball_wh_ratio_max = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<double>("ball_wh_ratio_max", "double", 0, "Ball White Area Ratio Max", "", &UnitedSoccerVisionReconfConfig::ball_wh_ratio_max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<double>("ball_wh_ratio_max", "double", 0, "Ball White Area Ratio Max", "", &UnitedSoccerVisionReconfConfig::ball_wh_ratio_max)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.ball_percent_white = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.ball_percent_white = 100;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.ball_percent_white = 0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("ball_percent_white", "int", 0, "Ball Percent White", "", &UnitedSoccerVisionReconfConfig::ball_percent_white)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::ParamDescription<int>("ball_percent_white", "int", 0, "Ball Percent White", "", &UnitedSoccerVisionReconfConfig::ball_percent_white)));
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(UnitedSoccerVisionReconfConfig::AbstractGroupDescriptionConstPtr(new UnitedSoccerVisionReconfConfig::GroupDescription<UnitedSoccerVisionReconfConfig::DEFAULT, UnitedSoccerVisionReconfConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<UnitedSoccerVisionReconfConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<UnitedSoccerVisionReconfConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    UnitedSoccerVisionReconfConfig __max__;
    UnitedSoccerVisionReconfConfig __min__;
    UnitedSoccerVisionReconfConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const UnitedSoccerVisionReconfConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static UnitedSoccerVisionReconfConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &UnitedSoccerVisionReconfConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const UnitedSoccerVisionReconfConfig &UnitedSoccerVisionReconfConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const UnitedSoccerVisionReconfConfig &UnitedSoccerVisionReconfConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const UnitedSoccerVisionReconfConfig &UnitedSoccerVisionReconfConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<UnitedSoccerVisionReconfConfig::AbstractParamDescriptionConstPtr> &UnitedSoccerVisionReconfConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<UnitedSoccerVisionReconfConfig::AbstractGroupDescriptionConstPtr> &UnitedSoccerVisionReconfConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const UnitedSoccerVisionReconfConfigStatics *UnitedSoccerVisionReconfConfig::__get_statics__()
  {
    const static UnitedSoccerVisionReconfConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = UnitedSoccerVisionReconfConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __UNITEDSOCCERVISIONRECONFRECONFIGURATOR_H__
