//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dynamic_params package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dynamic_params__UNITEDSOCCERRECONFCONFIG_H__
#define __dynamic_params__UNITEDSOCCERRECONFCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dynamic_params
{
  class UnitedSoccerReconfConfigStatics;

  class UnitedSoccerReconfConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(UnitedSoccerReconfConfig &config, const UnitedSoccerReconfConfig &max, const UnitedSoccerReconfConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const UnitedSoccerReconfConfig &config1, const UnitedSoccerReconfConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, UnitedSoccerReconfConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const UnitedSoccerReconfConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, UnitedSoccerReconfConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const UnitedSoccerReconfConfig &config) const = 0;
      virtual void getValue(const UnitedSoccerReconfConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T UnitedSoccerReconfConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (UnitedSoccerReconfConfig::* field);

      virtual void clamp(UnitedSoccerReconfConfig &config, const UnitedSoccerReconfConfig &max, const UnitedSoccerReconfConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const UnitedSoccerReconfConfig &config1, const UnitedSoccerReconfConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, UnitedSoccerReconfConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const UnitedSoccerReconfConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, UnitedSoccerReconfConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const UnitedSoccerReconfConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const UnitedSoccerReconfConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, UnitedSoccerReconfConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, UnitedSoccerReconfConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<UnitedSoccerReconfConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(UnitedSoccerReconfConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Pan_KP"==(*_i)->name){Pan_KP = boost::any_cast<double>(val);}
        if("Pan_KI"==(*_i)->name){Pan_KI = boost::any_cast<double>(val);}
        if("Pan_KD"==(*_i)->name){Pan_KD = boost::any_cast<double>(val);}
        if("Tilt_KP"==(*_i)->name){Tilt_KP = boost::any_cast<double>(val);}
        if("Tilt_KI"==(*_i)->name){Tilt_KI = boost::any_cast<double>(val);}
        if("Tilt_KD"==(*_i)->name){Tilt_KD = boost::any_cast<double>(val);}
        if("Pan_Step"==(*_i)->name){Pan_Step = boost::any_cast<double>(val);}
        if("Tilt_Step"==(*_i)->name){Tilt_Step = boost::any_cast<double>(val);}
        if("Pan_Kick"==(*_i)->name){Pan_Kick = boost::any_cast<double>(val);}
        if("Tilt_Kick"==(*_i)->name){Tilt_Kick = boost::any_cast<double>(val);}
        if("Body_KP"==(*_i)->name){Body_KP = boost::any_cast<double>(val);}
        if("KP_Ball_Pos_X"==(*_i)->name){KP_Ball_Pos_X = boost::any_cast<double>(val);}
        if("KP_Ball_Pos_Y"==(*_i)->name){KP_Ball_Pos_Y = boost::any_cast<double>(val);}
        if("KP_Compass_X"==(*_i)->name){KP_Compass_X = boost::any_cast<double>(val);}
        if("KP_Compass_Y"==(*_i)->name){KP_Compass_Y = boost::any_cast<double>(val);}
        if("KP_Compass_A"==(*_i)->name){KP_Compass_A = boost::any_cast<double>(val);}
      }
    }

    double Pan_KP;
double Pan_KI;
double Pan_KD;
double Tilt_KP;
double Tilt_KI;
double Tilt_KD;
double Pan_Step;
double Tilt_Step;
double Pan_Kick;
double Tilt_Kick;
double Body_KP;
double KP_Ball_Pos_X;
double KP_Ball_Pos_Y;
double KP_Compass_X;
double KP_Compass_Y;
double KP_Compass_A;

    bool state;
    std::string name;

    
}groups;



//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Pan_KP;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Pan_KI;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Pan_KD;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Tilt_KP;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Tilt_KI;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Tilt_KD;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Pan_Step;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Tilt_Step;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Pan_Kick;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Tilt_Kick;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Body_KP;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double KP_Ball_Pos_X;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double KP_Ball_Pos_Y;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double KP_Compass_X;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double KP_Compass_Y;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double KP_Compass_A;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("UnitedSoccerReconfConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const UnitedSoccerReconfConfig &__max__ = __getMax__();
      const UnitedSoccerReconfConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const UnitedSoccerReconfConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const UnitedSoccerReconfConfig &__getDefault__();
    static const UnitedSoccerReconfConfig &__getMax__();
    static const UnitedSoccerReconfConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const UnitedSoccerReconfConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void UnitedSoccerReconfConfig::ParamDescription<std::string>::clamp(UnitedSoccerReconfConfig &config, const UnitedSoccerReconfConfig &max, const UnitedSoccerReconfConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class UnitedSoccerReconfConfigStatics
  {
    friend class UnitedSoccerReconfConfig;

    UnitedSoccerReconfConfigStatics()
    {
UnitedSoccerReconfConfig::GroupDescription<UnitedSoccerReconfConfig::DEFAULT, UnitedSoccerReconfConfig> Default("Default", "", 0, 0, true, &UnitedSoccerReconfConfig::groups);
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Pan_KP = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Pan_KP = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Pan_KP = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Pan_KP", "double", 0, "Pan KP", "", &UnitedSoccerReconfConfig::Pan_KP)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Pan_KP", "double", 0, "Pan KP", "", &UnitedSoccerReconfConfig::Pan_KP)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Pan_KI = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Pan_KI = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Pan_KI = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Pan_KI", "double", 0, "Pan KI", "", &UnitedSoccerReconfConfig::Pan_KI)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Pan_KI", "double", 0, "Pan KI", "", &UnitedSoccerReconfConfig::Pan_KI)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Pan_KD = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Pan_KD = 1e-05;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Pan_KD = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Pan_KD", "double", 0, "Pan KD", "", &UnitedSoccerReconfConfig::Pan_KD)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Pan_KD", "double", 0, "Pan KD", "", &UnitedSoccerReconfConfig::Pan_KD)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Tilt_KP = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Tilt_KP = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Tilt_KP = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Tilt_KP", "double", 0, "Tilt KP", "", &UnitedSoccerReconfConfig::Tilt_KP)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Tilt_KP", "double", 0, "Tilt KP", "", &UnitedSoccerReconfConfig::Tilt_KP)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Tilt_KI = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Tilt_KI = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Tilt_KI = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Tilt_KI", "double", 0, "Tilt KI", "", &UnitedSoccerReconfConfig::Tilt_KI)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Tilt_KI", "double", 0, "Tilt KI", "", &UnitedSoccerReconfConfig::Tilt_KI)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Tilt_KD = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Tilt_KD = 1e-05;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Tilt_KD = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Tilt_KD", "double", 0, "Tilt KD", "", &UnitedSoccerReconfConfig::Tilt_KD)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Tilt_KD", "double", 0, "Tilt KD", "", &UnitedSoccerReconfConfig::Tilt_KD)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Pan_Step = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Pan_Step = 0.2;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Pan_Step = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Pan_Step", "double", 0, "Pan Step", "", &UnitedSoccerReconfConfig::Pan_Step)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Pan_Step", "double", 0, "Pan Step", "", &UnitedSoccerReconfConfig::Pan_Step)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Tilt_Step = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Tilt_Step = 0.5;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Tilt_Step = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Tilt_Step", "double", 0, "Tilt Step", "", &UnitedSoccerReconfConfig::Tilt_Step)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Tilt_Step", "double", 0, "Tilt Step", "", &UnitedSoccerReconfConfig::Tilt_Step)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Pan_Kick = -1.5;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Pan_Kick = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Pan_Kick = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Pan_Kick", "double", 0, "pan Kick", "", &UnitedSoccerReconfConfig::Pan_Kick)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Pan_Kick", "double", 0, "pan Kick", "", &UnitedSoccerReconfConfig::Pan_Kick)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Tilt_Kick = -2.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Tilt_Kick = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Tilt_Kick = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Tilt_Kick", "double", 0, "Tilt Kick", "", &UnitedSoccerReconfConfig::Tilt_Kick)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Tilt_Kick", "double", 0, "Tilt Kick", "", &UnitedSoccerReconfConfig::Tilt_Kick)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Body_KP = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Body_KP = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Body_KP = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Body_KP", "double", 0, "Body KP", "", &UnitedSoccerReconfConfig::Body_KP)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("Body_KP", "double", 0, "Body KP", "", &UnitedSoccerReconfConfig::Body_KP)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.KP_Ball_Pos_X = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.KP_Ball_Pos_X = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.KP_Ball_Pos_X = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("KP_Ball_Pos_X", "double", 0, "KP Ball Pos X", "", &UnitedSoccerReconfConfig::KP_Ball_Pos_X)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("KP_Ball_Pos_X", "double", 0, "KP Ball Pos X", "", &UnitedSoccerReconfConfig::KP_Ball_Pos_X)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.KP_Ball_Pos_Y = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.KP_Ball_Pos_Y = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.KP_Ball_Pos_Y = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("KP_Ball_Pos_Y", "double", 0, "KP Ball Pos Y", "", &UnitedSoccerReconfConfig::KP_Ball_Pos_Y)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("KP_Ball_Pos_Y", "double", 0, "KP Ball Pos Y", "", &UnitedSoccerReconfConfig::KP_Ball_Pos_Y)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.KP_Compass_X = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.KP_Compass_X = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.KP_Compass_X = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("KP_Compass_X", "double", 0, "KP Compass X", "", &UnitedSoccerReconfConfig::KP_Compass_X)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("KP_Compass_X", "double", 0, "KP Compass X", "", &UnitedSoccerReconfConfig::KP_Compass_X)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.KP_Compass_Y = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.KP_Compass_Y = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.KP_Compass_Y = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("KP_Compass_Y", "double", 0, "KP Compass Y", "", &UnitedSoccerReconfConfig::KP_Compass_Y)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("KP_Compass_Y", "double", 0, "KP Compass Y", "", &UnitedSoccerReconfConfig::KP_Compass_Y)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.KP_Compass_A = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.KP_Compass_A = 1.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.KP_Compass_A = 0.0;
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("KP_Compass_A", "double", 0, "KP Compass A", "", &UnitedSoccerReconfConfig::KP_Compass_A)));
//#line 274 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr(new UnitedSoccerReconfConfig::ParamDescription<double>("KP_Compass_A", "double", 0, "KP Compass A", "", &UnitedSoccerReconfConfig::KP_Compass_A)));
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 246 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(UnitedSoccerReconfConfig::AbstractGroupDescriptionConstPtr(new UnitedSoccerReconfConfig::GroupDescription<UnitedSoccerReconfConfig::DEFAULT, UnitedSoccerReconfConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<UnitedSoccerReconfConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<UnitedSoccerReconfConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    UnitedSoccerReconfConfig __max__;
    UnitedSoccerReconfConfig __min__;
    UnitedSoccerReconfConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const UnitedSoccerReconfConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static UnitedSoccerReconfConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &UnitedSoccerReconfConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const UnitedSoccerReconfConfig &UnitedSoccerReconfConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const UnitedSoccerReconfConfig &UnitedSoccerReconfConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const UnitedSoccerReconfConfig &UnitedSoccerReconfConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<UnitedSoccerReconfConfig::AbstractParamDescriptionConstPtr> &UnitedSoccerReconfConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<UnitedSoccerReconfConfig::AbstractGroupDescriptionConstPtr> &UnitedSoccerReconfConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const UnitedSoccerReconfConfigStatics *UnitedSoccerReconfConfig::__get_statics__()
  {
    const static UnitedSoccerReconfConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = UnitedSoccerReconfConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __UNITEDSOCCERRECONFRECONFIGURATOR_H__
